export const foodEmojis = [
  { emoji: '🐟', en: 'fish', ko: '생선' },
  { emoji: '🐚', en: 'spiral shell', ko: '소라게' },
  { emoji: '🐔', en: 'chicken', ko: '치킨' },
  { emoji: '🐖 ', en: 'pig', ko: '삼겹살' },
  { emoji: '🐄', en: 'cow', ko: '소' },
  { emoji: '🌾', en: 'sheaf of rice', ko: '쌀' },
  { emoji: '🌿', en: 'herb', ko: '허브' },
  { emoji: '🍇', en: 'grapes', ko: '포도' },
  { emoji: '🍈', en: 'melon', ko: '멜론' },
  { emoji: '🍉', en: 'watermelon', ko: '수박' },
  { emoji: '🍊', en: 'tangerine', ko: '귤' },
  { emoji: '🍋', en: 'lemon', ko: '레몬' },
  { emoji: '🍌', en: 'banana', ko: '바나나' },
  { emoji: '🍍', en: 'pineapple', ko: '파인애플' },
  { emoji: '🥭', en: ' mango', ko: '망고' },
  { emoji: '🍎', en: 'red apple', ko: '사과' },
  { emoji: '🍏', en: 'gr emoji: "",een apple', ko: '초록 사과' },
  { emoji: '🍐', en: 'pear', ko: '배' },
  { emoji: '🍑', en: 'peach', ko: '복숭아' },
  { emoji: '🍒', en: 'cherries', ko: '체리' },
  { emoji: '🍓', en: 'strawberry', ko: '딸기' },
  { emoji: '🫐', en: ' blueberries', ko: '블루베리' },
  { emoji: '🥝', en: 'kiwi fruit', ko: '키위' },
  { emoji: '🍅', en: 'tomato', ko: '토마토' },
  { emoji: '🫒', en: ' olive', ko: '올리브' },
  { emoji: '🥥', en: 'coconut', ko: '코코넛' },
  { emoji: '🥑', en: 'avocado', ko: '아보카도' },
  { emoji: '🍆', en: 'eggplant', ko: '가지' },
  { emoji: '🥔', en: 'potato', ko: '감자' },
  { emoji: '🥕', en: 'carrot', ko: '당근' },
  { emoji: '🌽', en: 'ear of corn', ko: '옥수수' },
  { emoji: '🌶', en: 'hot pepper', ko: '고추' },
  { emoji: '🫑', en: ' bell pepper', ko: '피망' },
  { emoji: '🥒', en: 'cucumber', ko: '오이' },
  { emoji: '🥬', en: 'leafy gr emoji: "",een', ko: '배추' },
  { emoji: '🥦', en: 'broccoli', ko: '브로콜리' },
  { emoji: '🧄', en: ' garlic', ko: '마늘' },
  { emoji: '🧅', en: ' onion', ko: '양파' },
  { emoji: '🥜', en: 'peanuts', ko: '땅콩' },
  { emoji: '🫘', en: ' beans', ko: '콩' },
  { emoji: '🌰', en: 'chestnut', ko: '밤' },
  { emoji: '🍞', en: 'bread', ko: '빵' },
  { emoji: '🥐', en: 'croissant', ko: '크로와상' },
  { emoji: '🥖', en: 'baguette bread', ko: '바게트' },
  { emoji: '🫓', en: 'flatbread', ko: '또띠아' },
  { emoji: '🥨', en: 'pretzel', ko: '프레첼' },
  { emoji: '🥯', en: 'bagel', ko: '베이글' },
  { emoji: '🥞', en: 'pancakes', ko: '팬케이크' },
  { emoji: '🧇', en: 'waffle', ko: '와플' },
  { emoji: '🧀', en: 'cheese wedge', ko: '치즈' },
  { emoji: '🍖', en: 'meat on bone', ko: '고기' },
  { emoji: '🍗', en: 'poultry leg', ko: '닭고기' },
  { emoji: '🥩', en: 'cut of meat', ko: '돼지고기' },
  { emoji: '🥓', en: 'bacon', ko: '베이컨' },
  { emoji: '🍔', en: 'hamburger', ko: '햄버거' },
  { emoji: '🍟', en: 'french fries', ko: '프렌치 프라이' },
  { emoji: '🍕', en: 'pizza', ko: '피자' },
  { emoji: '🌭', en: 'hot dog', ko: '핫도그' },
  { emoji: '🥪', en: 'sandwich', ko: '샌드위치' },
  { emoji: '🌮', en: 'taco', ko: '타코' },
  { emoji: '🌯', en: 'burrito', ko: '부리토' },
  { emoji: '🥙', en: 'stuffed flatbread', ko: '속이 가득찬 플랫브레드' },
  { emoji: '🥚', en: 'egg', ko: '달걀' },
  { emoji: '🍳', en: 'cooking', ko: '요리' },
  { emoji: '🥘', en: 'shallow pan of food', ko: '요리' },
  { emoji: '🍲', en: 'pot of food', ko: '찌개' },
  { emoji: '🫕', en: 'fondue', ko: '퐁듀' },
  { emoji: '🥣', en: 'bowl with spoon', ko: '그릇' },
  { emoji: '🥗', en: 'green salad', ko: '샐러드' },
  { emoji: '🍿', en: 'popcorn', ko: '팝콘' },
  { emoji: '🧈', en: 'butter', ko: '버터' },
  { emoji: '🧂', en: 'salt', ko: '소금' },
  { emoji: '🥫', en: 'canned food', ko: '통조림' },
  { emoji: '🍱', en: 'bento box', ko: '도시락' },
  { emoji: '🍘', en: 'rice cracker', ko: '쌀과자' },
  { emoji: '🍙', en: 'rice ball', ko: '주먹밥' },
  { emoji: '🍚', en: 'cooked rice', ko: '쌀' },
  { emoji: '🍛', en: 'curry rice', ko: '카레' },
  { emoji: '🍜', en: 'steaming bowl', ko: '면' },
  { emoji: '🍝', en: 'spaghetti', ko: '스파게티 파스타' },
  { emoji: '🍠', en: 'roasted sweet potato', ko: '고구마' },
  { emoji: '🍢', en: 'o emoji: "",den', ko: '어묵' },
  { emoji: '🍣', en: 'sushi', ko: '초밥' },
  { emoji: '🍤', en: 'fried shrimp', ko: '새우 튀김' },
  { emoji: '🍥', en: 'fish cake with swirl', ko: '소용돌이 모양 어묵' },
  { emoji: '🥮', en: 'moon cake', ko: '월병' },
  { emoji: '🍡', en: 'dango', ko: '경단' },
  { emoji: '🥟', en: 'dumpling', ko: '만두' },
  { emoji: '🥠', en: 'fortune cookie', ko: '포춘 쿠키' },
  { emoji: '🥡', en: 'takeout box', ko: '포장' },
  { emoji: '🦀', en: 'crab', ko: '게' },
  { emoji: '🦞', en: 'lobster', ko: '랍스터' },
  { emoji: '🦐', en: 'shrimp', ko: '새우' },
  { emoji: '🦑', en: 'squid', ko: '오징어' },
  { emoji: '🦪', en: 'oyster', ko: '굴' },
  { emoji: '🍦', en: 'soft ice cream', ko: '소프트 아이스크림' },
  { emoji: '🍧', en: 'shaved ice', ko: '셔벗 아이스크림' },
  { emoji: '🍨', en: 'ice cream', ko: '아이스크림' },
  { emoji: '🍩', en: 'doughnut', ko: '도넛' },
  { emoji: '🍪', en: 'cookie', ko: '쿠키' },
  { emoji: '🎂', en: 'birthday cake', ko: '케이크' },
  { emoji: '🍰', en: 'shortcake', ko: '조각 케이크' },
  { emoji: '🧁', en: 'cupcake', ko: '컵케이크' },
  { emoji: '🥧', en: 'pie', ko: '파이' },
  { emoji: '🍫', en: 'chocolate bar', ko: '초콜릿' },
  { emoji: '🍬', en: 'candy', ko: '사탕 캔디' },
  { emoji: '🍭', en: 'lollipop', ko: '롤리팝' },
  { emoji: '🍮', en: 'custard', ko: '커스터드 푸딩' },
  { emoji: '🍯', en: 'honey pot', ko: '꿀' },
  { emoji: '🍼', en: 'baby bottle', ko: '젖병' },
  { emoji: '🥛', en: 'glass of milk', ko: '우유' },
  { emoji: '☕', en: 'hot beverage', ko: '커피' },
  { emoji: '🫖', en: 'teapot', ko: '차' },
  { emoji: '🍵', en: 'teacup without handle', ko: '물' },
  { emoji: '🍶', en: 'sake', ko: '사케' },
  { emoji: '🍾', en: 'bottle with popping cork', ko: '코르크 병' },
  { emoji: '🍷', en: 'wine glass', ko: '와인' },
  { emoji: '🍸', en: 'cocktail glass', ko: '칵테일' },
  { emoji: '🍹', en: 'tropical drink', ko: '주스' },
  { emoji: '🍺', en: 'beer mug', ko: '맥주' },
  { emoji: '🍻', en: 'clinking beer mugs', ko: '맥주' },
  { emoji: '🥂', en: 'clinking glasses', ko: '와인' },
  { emoji: '🥃', en: 'tumbler glass', ko: '음료' },
  { emoji: '🧉', en: 'cup with straw', ko: '빨대' },
  { emoji: '🧊', en: 'ice', ko: '얼음' },
  { emoji: '🥢', en: 'chopsticks', ko: '젓가락' },
  { emoji: '🍽️', en: 'fork and knife with plate', ko: '식기' },
  { emoji: '🍴', en: 'fork and knife', ko: '식기' },
  { emoji: '🥄', en: 'spoon', ko: '숟가락' },
  { emoji: '🔪', en: 'kitchen knife', ko: '칼' },
  { emoji: '🫙', en: 'jar', ko: '병' },
  { emoji: '🏺', en: 'amphora', ko: '암포라' },
];
